# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---


Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [33]:
import numpy as np
x=np.arange(1,11)
print(x)


[ 1  2  3  4  5  6  7  8  9 10]


Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [34]:
a=np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
a=np.zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Exercise 3:¶
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [35]:
B = np.linspace(0, 5, 10)  
print(B)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [36]:
C = np.eye(5)        
print(C) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [6]:
e = np.random.random((4,4))  
print("E=",e)        

E= [[0.48805542 0.68229517 0.80982499 0.10738454]
 [0.71486217 0.73436165 0.13375862 0.49342031]
 [0.00096463 0.80452829 0.63379718 0.73429039]
 [0.19597298 0.37132256 0.15531395 0.34884894]]


Exercise 6:¶
Find the shape of a NumPy array.

In [7]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2,type(a2))
print(a2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
(3, 3)


Exercise 7:¶
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [8]:
numbers = np.arange(1, 17).reshape((4, 4))
print(numbers)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Find the data type of the elements in a NumPy array

In [37]:
 C= np.array([1, 2, 3])
D = np.array([1.2, 2.4, 3.5,6.7])
print(D.dtype)
print(c.dtype)

float64
int64


Exercise 9:¶
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [38]:
m=np.arange(1,101)
m[m%2==0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Exercise 10:¶
Generate a 6x6 matrix of random integers between 10 and 50.

In [39]:
x=np.random.randint(10,51,(6,6))
print(x)

[[15 30 16 39 43 23]
 [21 50 25 13 42 43]
 [25 10 20 14 46 26]
 [22 48 48 45 43 46]
 [30 16 24 22 19 26]
 [45 35 12 38 16 29]]


Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [40]:
a = np.array([[1,2,4,7], [5,6,7,8], [9,8,11,12]])
b = a[:2, 1:3]
print(a)
print(b)

[[ 1  2  4  7]
 [ 5  6  7  8]
 [ 9  8 11 12]]
[[2 4]
 [6 7]]


Exercise 12:¶
Calculate the sum of all elements in a NumPy array.

In [41]:
c=np.array([1,3,4,5,6,10])
print(np.sum(c))

29


Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [42]:
c=np.array([1,3,4,5,6,10])
print(np.mean(c))
print(np.std(c))
print(np.median(c))

4.833333333333333
2.7938424357067015
4.5


exercise 14:¶
Find the maximum and minimum values in a NumPy array.

In [31]:
D=np.random.randint(1,10,(3,3))
print(D)
C=np.max(D,axis=0)
F=np.max(D,axis=1)
E=np.max(D)
T=np.min(D,axis=0)
print(C)
print(F)
print(T)

[[4 7 3]
 [3 8 4]
 [1 3 5]]
[4 8 5]
[7 8 5]
[1 3 3]


Create a NumPy array of 20 random integers and find the index of the maximum value.

Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [30]:
x=np.random.randint(1,30,20)
print(x)
y=np.max(x)
print(np.argmax(x))
print(np.argmin(x))


[ 7  9  8  2  2  3 25  6 27  6  9  8 13 24 17 18  6 16  9  6]
8
3


Exercise 16:
Create a NumPy array and reverse its elements.

In [29]:
z=np.array([1,2,3,4,5])
print(z)
a=z[::-1]
print(a)

[1 2 3 4 5]
[5 4 3 2 1]


Exercise 17:¶
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [28]:
x=np.arange(1,10).reshape((3,3))
y=np.arange(4,13).reshape((3,3))
print(x)
print(y)
z=x*y
print(z)
np.multiply(x, y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[  4  10  18]
 [ 28  40  54]
 [ 70  88 108]]


array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [27]:
np.dot(x,y)

array([[16, 19],
       [36, 43]])

Exercise 18:
Create a diagonal matrix from a given 1D array.

In [26]:
U=np.array([1,2,4,5])
z=np.diagflat(U)
print(z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 5]]


Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [25]:
x=np.arange(1,5).reshape((2,2))
y=np.arange(4,8).reshape((2,2))
print(x)
print(y)
np.dot(x,y)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


array([[16, 19],
       [36, 43]])

Exercise 20:¶
Flatten a 2D NumPy array into a 1D array.

In [24]:
y=np.arange(2,6).reshape((2,2))
y.flatten()

array([2, 3, 4, 5])

Exercise 21:¶
Stack two NumPy arrays vertically.

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

Exercise 22:
Stack two NumPy arrays horizontally.

In [22]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [21]:

y = np.array([1,2,4,5,6,7,8])  
x = np.split(y, [2, 4, 5, 6])
print(x)



[array([1, 2]), array([4, 5]), array([6]), array([7]), array([8])]


Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [20]:
P=np.random.rand(1,10)
P_rounded=np.round(P, 2)
print(P_rounded)

[[0.84 0.57 0.26 0.64 0.1  0.68 0.55 0.27 0.39 0.56]]


Exercise 25:
Find the unique elements of a NumPy array.

In [19]:
w=np.array([2,3,4,5,7,1,2])
np.unique(w)

array([1, 2, 3, 4, 5, 7])

Exercise 26:¶
Replace all elements in a NumPy array that are less than a specific value with that value.

In [18]:
a1 = np.array([1, 2, 3, 10, 9, 5, 0, 8])
value = 3
a1[a1 < value] = value
print(a1)

[ 3  3  3 10  9  5  3  8]


Exercise 27:¶
Find the cumulative sum of the elements in a NumPy array.

In [17]:
a1 = np.array([1, 2, 3, 10, 9, 5, 0, 8])
np.cumsum(a1)

array([ 1,  3,  6, 16, 25, 30, 30, 38])

Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [16]:

a1 = np.array([1, 2, 3, 0,10, 9, 5, 0, 8,4,5])
np.count_nonzero(a1)


9

Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [15]:

M = np.random.randint(0, 30,10)
np.sort(M)

array([ 1,  2, 14, 17, 18, 19, 21, 25, 27, 28])

Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [14]:

E = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(np.sum(E, axis=1))
print(np.sum(E, axis=0))

[ 6 15 24]
[12 15 18]


Exercise 31:¶
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

In [13]:
x = np.random.rand(2, 2) * 10
normalized=(x-np.max(x))/(np.max(x)-np.min(x))
print(normalized)

[[-0.23246081 -1.        ]
 [-0.25452338  0.        ]]


Exercise 32:¶
Create two NumPy arrays and find the dot product.

In [12]:
a=np.array([1,2,3,4])
b=np.array([2,4,5,7])
z=np.dot(a,b)
print(z)

53


Exercise 33:¶
Find the trace of a square NumPy matrix.

In [10]:
z=np.array([[2,3],[4,5]])
np.trace(z)

7

Exercise 34:
Create a 2D array and swap two rows.

In [11]:
N = np.array([[1, 2, 3],[4, 5, 6]])
N[[0, 1]] = N[[1, 0]]
print(N)

[[4 5 6]
 [1 2 3]]


Exercise 35:¶
Create a 1D NumPy array and convert it into a column vector.

In [45]:
F=np.array([2,3,4,5])
print(F.reshape(-1,1))

[[2]
 [3]
 [4]
 [5]]


Exercise 36:
Find the determinant of a 3x3 matrix.

In [5]:

D = np.array([[1, 2, 4],[3, 2, 1],[4, 7, 9]])
print(D)
print( np.linalg.det(D))


[[1 2 4]
 [3 2 1]
 [4 7 9]]
17.0


In [ ]:
Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [29]:

matrix = np.array([[1, 2],[4, 3]])
y,z = np.linalg.eig(matrix)
print("the eigen values are:",y)
print("the eigen vectors are:",z)

the eigen values are: [-1.  5.]
the eigen vectors are: [[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


Exercise 38:
Solve a system of linear equations using NumPy.

In [33]:

M = np.array([[1, 1],[1, -1]])
N= np.array([2, 4])

print(np.linalg.solve(M, N))


[ 3. -1.]


Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

In [39]:

V= np.array([[1, 2, 4, 4],[5, 3, 7, 8],[9, 10, 17, -2],[0, 0, 1, 2]])
print(V)
Y = np.diag(V)
print(Y)

[[ 1  2  4  4]
 [ 5  3  7  8]
 [ 9 10 17 -2]
 [ 0  0  1  2]]
[ 1  3 17  2]
